import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
(function() {
	try {
		if (typeof __filename !== 'undefined' && __filename) {
			var pathToFileURL = require('url').pathToFileURL;
			globalThis.import_meta_url = pathToFileURL(__filename).href;
			console.log('[import.meta.url polyfill] Set to:', globalThis.import_meta_url);
		} else {
			console.warn('[import.meta.url polyfill] __filename is not available, using fallback');
			globalThis.import_meta_url = 'file:///obsidian-plugin/main.js';
		}
	} catch (e) {
		console.error('[import.meta.url polyfill] Error:', e);
		globalThis.import_meta_url = 'file:///obsidian-plugin/main.js';
	}
})();
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	define: {
		'import.meta.url': 'globalThis.import_meta_url',
	},
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
